### ISSUE TITLE
"Cannot open shared object file: No such file or directory" error

### ISSUE THREAD

**Issue by theEpicjosh** [ivan-hc/Spotify-appimage#2]
When I go to run the Spotify AppImage file on the terminal, I get this error:

```
/tmp/.mount_SpotifdAiohP/opt/spotify/spotify: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
```

I run _Arch Linux / GNOME_ and the terminal I used was _Konsole_.
If you need any additional information, please let me know.

**Comment by ivan-hc** [comment]
try now

**Comment by theEpicjosh** [comment]
It does not work, still. I get the error:
`/tmp/.mount_SpotifMJMFli/opt/spotify/spotify: error while loading shared libraries: libayatana-indicator3.so.7: cannot open shared object file: No such file or directory`

**Comment by ivan-hc** [comment]
I'm still unable to reproduce the issue... works for me... try to update from about 5 minutes, I just dded a commit.

**Comment by theEpicjosh** [comment]
Do you think having Spotify on Flatpak may interfere?

**Comment by ivan-hc** [comment]
Also tell me if you have oother AppImage handlers on the system that may cause problems from terminal (i.e. AppImageLauncher, `appimaged`/`appimagelauncherd`)... if so, try to remove it and reboot.

> Do you think having Spotify on Flatpak may interfere?

Nope, the issue is with a shared library that it was unable to see. Now I changed the LD_LIBRARY_PATH to use only its internal libraries.

**Comment by theEpicjosh** [comment]
It should just run directly from my zsh terminal. I don't believe I have any specific programs for *running* appimages.

**Comment by ivan-hc** [comment]
is it working now?

**Comment by theEpicjosh** [comment]
No, I get:
```
/tmp/.mount_SpotifGhmfac/opt/spotify/spotify: error while loading shared libraries: libayatana-indicator3.so.7: cannot open shared object file: No such file or directory
```

**Comment by ivan-hc** [comment]
Try to extract the AppImage
```
./*AppImage --appimage-extract
```
then extract the content of this package https://archlinux.org/packages/extra/x86_64/libayatana-indicator/download/ in the squashfs-root directory

then run the AppRun script and see if this fixes the issue

**Comment by theEpicjosh** [comment]
I still get this error.
```
[Redacted Directory] ... /squashfs-root/opt/spotify/spotify: error while loading shared libraries: libayatana-ido3-0.4.so.0: cannot open shared object file: No such file or directory
```

**Comment by ivan-hc** [comment]
try to extract also this https://archlinux.org/packages/extra/x86_64/ayatana-ido/download/

each time you get an error do a search like this
```
libayatana-ido3-0.4.so.0 archlinux
```
then report the packages until the app works again... so i can fix it

**Comment by theEpicjosh** [comment]
I merged the contents in the `ayatana-ido` and the `libyatana-indicator` folders inside the `squashfs-root` folder and it works!

**Comment by ivan-hc** [comment]
the new release will be ready in 2 minutes

**Comment by justin025** [comment]
issue persists

`./Spotify-1.2.63.394.g126b0d89-x86_64.AppImage --appimage-extract-and-run`
/tmp/appimage_extracted_c655233b0ecde447ec95fec20ea95ec1/usr/bin/spotify: error
while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory

**Comment by ivan-hc** [comment]
> issue persists
> 
> `./Spotify-1.2.63.394.g126b0d89-x86_64.AppImage --appimage-extract-and-run` /tmp/appimage_extracted_c655233b0ecde447ec95fec20ea95ec1/usr/bin/spotify: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory

hi, i got this error instead
```
(spotify:3351): libayatana-appindicator-WARNING **: 00:41:45.619: libayatana-appindicator is deprecated. Please use libayatana-appindicator-glib in newly written code.
```
...but the Appimage works.

**Comment by justin025** [comment]
You likely have libayatana-appindicator3.so.1 installed on your base system which is why you cannot reproduce the error. On minimal systems without the lib the spotify appimage is not able to launch.

**Comment by ivan-hc** [comment]
> You likely have libayatana-appindicator3.so.1 installed on your base system which is why you cannot reproduce the error. On minimal systems without the lib the spotify appimage is not able to launch.
> […](#)

Exporting LD_LIBRARY_PATH seemed to cause problems in this and other AppImages I build, based on user reports, so I stopped adding it to the AppRun. I'm also distributing a Spotify AppImage built from the SNAP package, so that library is already included in the package.

I don't know. While the program won't run for you because that library can't be loaded, I can run it, but I get a message saying that the library is deprecated.

Snap2AppImage is certainly my least efficient method for packaging an AppImage, but it's also the one that uses the most "native" packages possible (Spotify is an electron app, after all; it should work out of the box).

Since I can't reproduce the problem, I recommend extracting the AppImage and running some tests by editing the AppRun file.

**Comment by Keeeeeeeen** [comment]
Still exhibited in latest release. Installing libayatana-appindicator-gtk3 on the base system fixes the issue. I suspect this library needs to be included in the AppImage and is missing.

**Comment by ivan-hc** [comment]
The issue come from upstream. They should fix it in the Snap package.

Now releases available are stable, edge and candidate. Try with one of them... or use a snapshot.

If you have AM or AppMan, I have just updated the script for stable https://github.com/ivan-hc/AM/commit/cfc56a2bba6002f27380f1eb5a7d4a93f5bffcc7 so you need to re-install it.

After reinstall, try with the option `downgrade` or `--rollback` and choose a previous version, like this:

<img width="747" height="654" alt="Image" src="https://github.com/user-attachments/assets/89a00d78-12ce-4880-b3df-68368fc291c6" />

Or alternatively, use the `spotify-edge` or `spotify-candidate` package.

I only repackage the content of the official Snap. It is not my fault if the base package is broken.

However, I could fix it by compile such library statically myself... but what if they fix the issue and we end to have two libraries in conflict?
